on: [push]
name: AzurePowerShellSample

jobs:

  build:
    runs-on: 'windows-latest'
    steps:
    
    - name: Login via Az module
      uses: azure/login@v1.1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_2}}
        enable-AzPSSession: true 
        
    - name: Run Azure PowerShell script
      uses: azure/powershell@v1
      with:
        inlineScript: |
          Get-AzResource | ft
          
        azPSVersion: '3.1.0'
        
    - name: Check out the code
      uses: actions/checkout@v1
      
    - name: Run Azure PowerShell script 2
      uses: azure/powershell@v1
      with:
        inlineScript: |
          Powershell.exe -File .\myscripts\Code.ps1 -websiteName "https://testingwebapp10.azurewebsites.net" -sourceDir "".\testfiles"" -resourceGroupName Development
          
        azPSVersion: '3.1.0'

    #- uses: actions/checkout@v1
    #- uses: azure/powershell@v1
    #- name: Build
    #  shell: powershell
     # run: |
      #  powershell .\myscripts\helloworld.ps1
        
    
