on: [push]
name: AzurePowerShellSample

jobs:

  build:
    runs-on: 'windows-latest'
    steps:
    
    - name: Login via Az module
      uses: azure/login@v1.1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true 

    - uses: actions/checkout@v1
    - name: Build
      shell: pwsh
      run: |
        .\myscripts\install.ps1
    
